import { makeEnum } from "../utils/enum"
import * as Icons from "../../assets/icons"

export const StartAnimation = makeEnum({
  Hover: "hover",
  HoverInfinite: "hover_infinite",
  Click: "click",
  Press: "press",
  Infinite: "infinite",
})

export const AnimationType = makeEnum({
  Bounce: "bounce",
  Float: "float",
  Slide: "slide",
  RotateMiddle: "rotate_middle",
  Rotate: "rotate",
})

export const IconType = makeEnum({
  ShieldAdmin: "ShieldAdmin",
  Airplane: "Airplane",
  ArrowDown: "ArrowDown",
  ArrowLeft: "ArrowLeft",
  ArrowRight: "ArrowRight",
  ArrowUp: "ArrowUp",
  Bookmark: "Bookmark",
  Bookmarks: "Bookmarks",
  Check: "Check",
  Circles: "Circles",
  ClockLoading: "ClockLoading",
  Clock: "Clock",
  Code: "Code",
  Formation: "Formation",
  Lamp: "Lamp",
  LineChart: "LineChart",
  Medal: "Medal",
  LogOut: "LogOut",
  Loading: "Loading",
  Menu: "Menu",
  Mouse: "Mouse",
  Save: "Save",
  Star: "Star",
  Thunder: "Thunder",
  UserInsideShield: "UserInsideShield",
  Linkedin: "Linkedin",
  Whatsapp: "Whatsapp",
  Email: "Email",
  Github: "Github",
  Close: "Close",
  Trash: "Trash",
  Key: "Key",
  Refresh: "Refresh",
  Eye: "Eye",
  EyeOff: "EyeOff",
  Grid: "Grid",
  Home: "Home",
  Search: "Search",
  Settings: "Settings",
  User: "User",
  Users: "Users",
  Notification: "Notification",
  Payments: "Payments",
  Instagram: "Instagram",
  Facebook: "Facebook",
  Trophy: "Trophy",
  Checklist: "Checklist",
})

export const iconMap = {
  [IconType.ShieldAdmin]: Icons.ShieldAdmin,
  [IconType.Airplane]: Icons.Airplane,
  [IconType.ArrowDown]: Icons.ArrowDown,
  [IconType.ArrowLeft]: Icons.ArrowLeft,
  [IconType.ArrowRight]: Icons.ArrowRight,
  [IconType.ArrowUp]: Icons.ArrowUp,
  [IconType.Bookmark]: Icons.Bookmark,
  [IconType.Bookmarks]: Icons.Bookmarks,
  [IconType.Check]: Icons.Check,
  [IconType.Circles]: Icons.Circles,
  [IconType.ClockLoading]: Icons.ClockLoading,
  [IconType.Clock]: Icons.Clock,
  [IconType.Code]: Icons.Code,
  [IconType.Formation]: Icons.Formation,
  [IconType.Lamp]: Icons.Lamp,
  [IconType.LineChart]: Icons.LineChart,
  [IconType.Medal]: Icons.Medal,
  [IconType.LogOut]: Icons.LogOut,
  [IconType.Loading]: Icons.Loading,
  [IconType.Menu]: Icons.Menu,
  [IconType.Mouse]: Icons.Mouse,
  [IconType.Save]: Icons.Save,
  [IconType.Star]: Icons.Star,
  [IconType.Thunder]: Icons.Thunder,
  [IconType.UserInsideShield]: Icons.UserInsideShield,
  [IconType.Linkedin]: Icons.Linkedin,
  [IconType.Whatsapp]: Icons.Whatsapp,
  [IconType.Email]: Icons.Email,
  [IconType.Github]: Icons.Github,
  [IconType.Close]: Icons.Close,
  [IconType.Trash]: Icons.Trash,
  [IconType.Key]: Icons.Key,
  [IconType.Refresh]: Icons.Refresh,
  [IconType.Eye]: Icons.Eye,
  [IconType.EyeOff]: Icons.EyeOff,
  [IconType.Grid]: Icons.Grid,
  [IconType.Home]: Icons.Home,
  [IconType.Search]: Icons.Search,
  [IconType.Settings]: Icons.Settings,
  [IconType.User]: Icons.User,
  [IconType.Users]: Icons.Users,
  [IconType.Notification]: Icons.Notification,
  [IconType.Payments]: Icons.Payments,
  [IconType.Instagram]: Icons.Instagram,
  [IconType.Facebook]: Icons.Facebook,
  [IconType.Trophy]: Icons.Trophy,
  [IconType.Checklist]: Icons.Checklist,
}
